name: release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

permissions:
  contents: write
  id-token: write

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.release-version.outputs.version }}
    steps:
      - name: Get the release version from the tag
        id: release-version
        shell: bash
        run: echo "version=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
      - name: Create draft GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release-version.outputs.version }}
          name: ${{ steps.release-version.outputs.version }}
          draft: true

  build-release:
    name: build-release
    needs: create-release
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [windows-2025, macos-15, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    env:
      RG_VERSION: ${{ needs.create-release.outputs.version }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - name: Compute node modules cache key
        id: nodeModulesCacheKey
        run: echo "value=$(node packages/build/src/computeNodeModulesCacheKey.ts)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v6
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ runner.arch }}-cacheNodeModules-${{ steps.nodeModulesCacheKey.outputs.value }}
      - name: npm ci
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm test
      - run: npm run build
      - run: npm run lint
      - name: Publish package to npm
        if: matrix.os == 'ubuntu-24.04'
        run: npm publish --access public --provenance
        working-directory: ./.tmp/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish GitHub release
        if: matrix.os == 'ubuntu-24.04'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit "${{ needs.create-release.outputs.version }}" --draft=false
